### PR TITLE
Promises

### PR DESCRIPTION
**Pull request by thecodershome**
Added promise object `gpio.promise`, which wraps setup, read, write, destroy in promises. 

Example from last PR
```js
var gpio = require('rpi-gpio.js'),
    gpio_p = gpio.promise;

gpio_p.setup(7, gpio.DIR_IN)
  .then(() => {
    return gpio_p.read(7)
  })
  .then((value) => {
    console.log('The value is ' + value);
  })
`

### CODE REVIEW

**Comment by JamesBarwell** [comment]
Excellent, this looks really good. Give me a little time to have a go myself and update the readme. I'll aim to get it merged in the next week.

**Comment by kkota1** [comment]
Bump

**Comment by johankj** [comment]
Any updates @JamesBarwell?

**Comment by JamesBarwell** [comment]
My only update is to apologise for dawdling so much. I have just got back from a holiday and hope to get on to this very soon.

I'm also considering some kind of beta branch for this project so that PRs like this can be made available much more quickly.

**Comment by JamesBarwell** [comment]
This has been merged and published as `0.9.0`.

Huge thanks for doing the work and many apologies again for being so slow to respond. I have various good excuses but I won't clutter the thread with my personal life!

I'm going to have a think about what to do for documentation and how much to push this new API. There's a very good case for this being the primary interface to the module, given how many users are new to node and struggle with the err-back functions.

**Pull request merged**
