### PR TITLE
not linux platform GPIO simulation

### PR DESCRIPTION
**Pull request by albiper**
All GPIO command simulated on not-linux platform

Useful for debugging while developing on Windows platform eg.

### CODE REVIEW

**Comment by albiper** [comment]
@JamesBarwell will you ever complete this PR?

**Comment by JamesBarwell** [comment]
Thanks for contributing, but sorry I'm not going to merge it. It's beyond the scope of this project to "work" on non-Linux systems and given I already don't have time to actively maintain it, it's not something I'd wish to try and support.

What problem are you trying to solve with this patch? Given it won't work on non-Linux systems anyway, could you solve it by swapping out this module in your own code instead?

**Comment by albiper** [comment]
Do you develop your code directly on the Raspberry? I use vscode on other devices and don't think I am the only. In that case is impossible to run it step by step because your library throws errors

p.s. you could have said that 3 years ago instead of leaving the PR open indefinitely

**Comment by JamesBarwell** [comment]
I've only developed this module on Linux computers (using the test suite) and the Pi itself. I don't have the facility to test it in other environments and therefore am not willing to say its officially supported (see the [note in the readme](https://github.com/JamesBarwell/rpi-gpio.js/tree/master?tab=readme-ov-file#dependency)). Though I was under the impression from others that it did work on Windows - see #93.

If you mean developing an application that uses this module - as said, my expectation is that it should be possible to mock out this module in your own code. Another possible option in Windows would be to develop using WSL2 or containers.

Sorry it took so long to reply. But I have other commitments and no longer use it myself (I first wrote it 12 years ago when little else was available!). I updated the readme previously to try to highlight this.

**Pull request closed without merging**
