### PR TITLE
Add typescript declarations

### PR DESCRIPTION
**Pull request by pascalmartin**
Hi

I use typescript in my project and i made the typescript declarations file for rpi-gpio module,

### CODE REVIEW

**Comment by JamesBarwell** [comment]
Thanks for the contribution. But this isn't a typescript project, and I definitely do not want to be obliged to support keeping these definitions up to date every time the implementation changes.

**Comment by benbrunton** [comment]
It may be more appropriate to submit this update to the Definitely Typed repository. https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by oveddan** [comment]
I wish this supported typescript.  WIthout typescript this library is unusable.  It doesn't have to be a typescript project to support typescript.

**Comment by JamesBarwell** [comment]
Over 2 years since this PR was closed and still no one submitted the definitions to DefinitelyTyped, despite parscalmartin having done the work.

I'm going so suggest that 1) not many users want this, 2) if there are no TS users with time to maintain the definitions, that just supports my comment that it's not reasonable to expect me and other contributors to this project to do it.

**Pull request closed without merging**
